### ISSUE TITLE
Update Payment Methods reactivates all methods

### ISSUE THREAD

**Issue by padrini** [mollie/Shopware#134]
With the newest version (1.7.1) it's possible to update the payment methods when the plugin is active, only when doing this the settings of which one was active and which one was deactivated are overwritten. 

So if you would do this on a live site the customers would have more payment methods available to them then you as a developer of shop owner want and those might even not be activated or configured inside Mollie.

The expected behauviour here would be that the methods are update but that their active state stays atleast the same.

**Comment by boxblinkracer** [comment]
Hi

oh, ouch, 
that seems to be deeper integrated.
we are currently improving onboarding stuff, so the encapsulation with that button was the first step

definitely makes sense, and should not happen
ill add a ticket, test case and make sure it gets done soon

thank you so much for helping

**Comment by padrini** [comment]
Hi Christian,

No problem, I said I did know where to find you if there were any problems ;) 

Hope to see this begin fixed soon, then we can push this update to live.

**Comment by boxblinkracer** [comment]
:) 

so i cant hide anymore, haha

cheers

**Comment by SandyMental** [comment]
Is it safe to update? As I understand the update of the payment methods is triggered by user action only?
Now that I know I shouldnt use this feature until it is fixed, I can live with it. 
 We would need the fix for the duplicated orders (MOL-135)

**Comment by boxblinkracer** [comment]
Hi
generally yes it only applies if you manually update
the duplicate order part is fixed, but we just found out that shopware might also sends mails in that case
(already almost starting to fix)

heres a full explanation what is actually happening, because its not really clear
https://github.com/mollie/Shopware/wiki/Known-Issues

**Comment by boxblinkracer** [comment]
Hi
so good news
i am already preparing a fix:
https://github.com/mollie/Shopware/pull/135

so the major problem is, that duplicate calls to Shopware happen (duplicate orders), which actually must never happen...so weird, so 1.7.1 has that fix, now i saw that Shopware does always send order confirmation mails, even though its already existing, and i didnt have that on my test list with the mail,...now it is...including fixed and (almost) verified
thinking about doing another small release this week

**Comment by SandyMental** [comment]
so just one line to fix this? is it save to add this manually  now or better wait if there is more to come?

**Comment by boxblinkracer** [comment]
basically yes, the saveOrder does internally correctly skip creating new ones, but always sends an email which is....not that good i think...but it is like it is
so this ones just an early return to do "nothing" and keep on working on that order number

still i would double and triple check it with QA tomorrow, so i would wait, and if it works i would do a small release

the general future approach would then be done by probably skipping the whole process on existing orders, now that we know that this sometimes happens..but that takes a bit more than the short time of a hotfix :)

**Comment by boxblinkracer** [comment]
good morning
did some (lots of) tests today for that 1 liner, did work as expected and was released with 1.7.2 today
please keep in mind this is just for the duplicate confirmation mail fix

this issue (payment method import) will be done with an upcoming release
was too risky for today, sorry

**Comment by boxblinkracer** [comment]
Hi
the mports have been refactored and improved with this PR:
https://github.com/mollie/Shopware/pull/137

**Comment by boxblinkracer** [comment]
hey there
an improved installation logic has been released with 1.7.3 which should fix all this :)

thanks for letting us know

**Comment by boxblinkracer** [comment]
i forgot to add this link - its the user guide
https://github.com/mollie/Shopware/wiki/Payment-Methods
