### ISSUE TITLE
Invalid order ID: ''. An order ID should start with 'ord_'.

### ISSUE THREAD

**Issue by klausmad** [mollie/Shopware#19]
Hi together,

use the newest mollie plugin 1.5.9 for shopware on shopware 5.6.4 / PHP 7.2.22 and got this message in shopware plugin production log:

{
  "exception": "[object] (Mollie\\Api\\Exceptions\\ApiException(code: 0): Invalid order ID: ''. An order ID should start with 'ord_'. at /vendor/mollie/mollie-api-php/src/Endpoints/OrderEndpoint.php:65)"
}

This exception happend while a credit card payment was done by customer in frontend. The credit card payment had success.

At the moment we do NOT use Klarna Pay later, we use only applepay, creditcard, paypal, sofort, eps.

The Plugin settings are done like this (live modus)

![grafik](https://user-images.githubusercontent.com/22545981/79097173-559dee00-7d5f-11ea-8c5b-767398d44240.png)

Is this any issue or can we ignore this message ?

BR Klaus

**Comment by milan-kiener** [comment]
Hey Klaus,

If you change "Bestellung erstellen bevor Abschluss der Zahlung" to "Ja" You should not have this problem. 

Still its an error we need to fix. Thank you for bringing it to our attention. I will submit this issue to development.

Best regards,

Milan Mooibroek

**Comment by julian-kiener** [comment]
Hello Klaus,

Is this still an issue? If so can you give us a scenario where this error comes up? We don't get it reproduced at this moment.

Best regards,

Julian Hessels

**Comment by florianliebig** [comment]
@julian-kiener We are getting the same error:

Invalid order ID: ''. An order ID should start with 'ord_'.

{
  "exception": "[object] (Mollie\\Api\\Exceptions\\ApiException(code: 0): Invalid order ID: ''. An order ID should start with 'ord_'. at /vendor/mollie/mollie-api-php/src/Endpoints/OrderEndpoint.php:65)"
}

When I look at the timestamp it seems to be in the moment the Shopware Order is created. 
![image](https://user-images.githubusercontent.com/10775702/85507893-5a024500-b5f3-11ea-8aa6-59ed78df0526.png)

**Comment by boxblinkracer** [comment]
Hallo an alle
Wir sind nun neu im Team....ist das hier noch aktuell?
