### ISSUE TITLE
Exception when cancelling payment

### ISSUE THREAD

**Issue by jurriaanr** [mollie/Shopware#20]
On a headless environment we redirect you to the mollie payment (test) page. When we cancel the order there, this happens:

![image](https://user-images.githubusercontent.com/7426848/79482198-cae41a00-8010-11ea-97ce-6ddd6e4e1a85.png)

State EFBFBDEFBFBDEFBFBD61EFBFBD504ADE also being: cancelled

So it looks to go from cancelled to cancelled

**Comment by reindernl** [comment]
Hello,

Thanks for contacting us. The issue you explain is an issue with the Shopware 6 version of the plugin. We have a seperate repository for that: https://github.com/mollie/Shopware6.

In regard to your question. I guess the plugin needs to do an extra check if the transition can be made. I'm not quite sure if Shopware provides us with that information, but we'll check. I've created a bug-issue on our backlog, so it will be picked up soon.

Although this error shouldn't be thrown, it shouldn't cause issues in production mode as far as I know. Nevertheless, it's an unnecessary error and we'll try to prevent it from being thrown in the next release.
