### ISSUE TITLE
Shopware order number is no longer counted +1 for each order

### ISSUE THREAD

**Issue by klausmad** [mollie/Shopware#21]
Since we have Mollie Plugin, the Shopware order number is no longer counted +1 for each order. 

The order number is counted up at completely irregular intervals, i.e. +4, + 8, + 2, + 3 without logic, so that one has to assume that Mollie is already counting up for each shopping cart (order cancellation) even though no payment has been made. 
I have sent more information to Mollie Support with email today. 

Please check the Mollie plugin to this effect, normaly that Shopware Standard would be to count up +1 for every successful order. Its not usefull if Mollie count every "cart" +1, it is only usefull to count every sucessfull order.

![grafik](https://user-images.githubusercontent.com/22545981/81595470-cd911f80-93c2-11ea-8d80-7dcb1f733a32.png)

We started with Mollie just some weeks ago, so you see exactly in the backend the difference how shop was counted before Mollie (+1 each order) and no today.

Mollie Plugin Version 1.5.10

Shopware Version 5.6.6

My settings
 
![grafik](https://user-images.githubusercontent.com/22545981/81594875-dfbe8e00-93c1-11ea-82f4-0eedfef89b97.png)

See this Example:

![grafik](https://user-images.githubusercontent.com/22545981/81596354-375df900-93c4-11ea-9979-77476477ef01.png)

Database mol_sw_transactions: why count +4 for next order ??

![grafik](https://user-images.githubusercontent.com/22545981/81596380-417ff780-93c4-11ea-9bd8-11c5f996eb4f.png)

Database s_order

![grafik](https://user-images.githubusercontent.com/22545981/81596681-c834d480-93c4-11ea-8033-6e6d42591719.png)

BR Klaus

**Comment by milan-mooibroek** [comment]
Hey Klaus, 

This issue depends on the plugin settings. Currently its standard that Shopware also saves orders that are cancelled. In the settings of the plugin you have an option to turn this on or off.

![Schermafbeelding 2020-05-15 om 10 16 19](https://user-images.githubusercontent.com/64866242/82028132-84c4b980-9695-11ea-99ed-6fe1c168cf8e.png)

If you turn this option on it will save every order and keep counting incrementally. If its off it will not save the order. But the number is used. So thats why it seems like the numbers are skipping at a random interval, But the orders in between are cancelled orders.

If you want personal support with the plugin contact us at support@kiener.nl

**Comment by milan-kiener** [comment]
Hey Klaus, 

This issue depends on the plugin settings. Currently its standard that Shopware also saves orders that are cancelled. In the settings of the plugin you have an option to turn this on or off.

![Schermafbeelding 2020-05-15 om 10 16 19](https://user-images.githubusercontent.com/65392700/82028804-63b09880-9696-11ea-86f5-d04f305da103.png)


If you turn this option on it will save every order and keep counting incrementally. If its off it will not save the order. But the number is used. So thats why it seems like the numbers are skipping at a random interval, But the orders in between are cancelled orders.

If you want personal support with the plugin contact us at support@kiener.nl

Best regards,

Milan Mooibroek

**Comment by klausmad** [comment]
Hi,

thanks for quick answer.

So as you wrote now I set this option to yes, is this correct ? (red marked)

So I will test it, if the order numbers are now corrct.

Can you please give me a short description oft he blue marked options (see snipping) so I can better understand the functcion behind the settings and please say what will be the best default setting.

THX BR Klaus

![grafik](https://user-images.githubusercontent.com/22545981/82046485-44733480-96b1-11ea-8e2c-d6fde8661293.png)


PS: Suggestion (already deposited) It would be urgent to have a proper German SW plugin description which describes the different options and their effects.

It was just a wrong attitude at the moment ... but because this is not described anywhere, other SW customers are sure to do the same.

It would be better and more efficient to make a good Shopware plugin description and save yourself dozens of support inquiries ... right? :-)

**Comment by milan-kiener** [comment]
Hey Klaus,

"Lader automatisch zuruckzetsen nach ein fehigeschlagener zahlung": After a failed payment the order stock is set back. This is so you need less manual control on the failed payments (since product wont be delivered).

"Bestellstatus von Mollie ubernehmen" : Copy the order status from mollie. If you change the order status at Mollie it will be changed in Shopware aswel. 

“Fehigeschlagene Bestellungen automatisch stornieren”: When you choose to save all orders before the payment is done (which is another setting in the configuration) you can choose to automatically cancel these orders if payment fails. As you might not want to save orders in your administration if the payment of that order has failed. When the customer chooses to pay with another payment method, a new order is created.


Yes we will update the german translations soon :) 

Best regards,

Milan Mooibroek

**Comment by boxblinkracer** [comment]
Hallo an alle
Wir sind nun neu im Team...ist dieses Problem noch aktuell?
