### ISSUE TITLE
Help wanted - Change return URL

### ISSUE THREAD

**Issue by githuphub** [mollie/Shopware#216]
Hi,

We made several changes to our checkout process, we removed the last /confirm/ step from the process. Now everything worked when we were still at 1.7.0 (oops) because we made a change in "function redirectBack" , I just updated to 1.8.4 but now when an order is cancelled people are redirected to /confirm/ because that's probably the default return for Mollie.

Can you tell me where to find the new function/code that handles the return? 

Thank you!

**Comment by githuphub** [comment]
Edit: Found it, not sure how I missed it in my first searches.

**Comment by boxblinkracer** [comment]
hi
ok great that you have found it
it should now stick with that way, but we had to change a lot to make it stable in the end :)
