### ISSUE TITLE
Shopware Update 5.7.0 - Declaration of MollieShopware\Components\Logger\MollieLogger

### ISSUE THREAD

**Issue by shopkueche** [mollie/Shopware#219]
After the update to Shopware 5.7.0 went the Shop offline with the following error code.

Fatal error: Declaration of MollieShopware\Components\Logger\MollieLogger::debug($message, array $context = Array) must be compatible with Monolog\Logger::debug($message, array $context = Array): void in ../custom/plugins/MollieShopware/Components/Logger/MollieLogger.php on line 66

Solution right now: 
Deactivate the Mollie Plugin and clear cache

**Comment by boxblinkracer** [comment]
Hi

thank you for this

the new release 5.7 has been released today,
there will of course be support for it, but at the moment its not officially supported

hope to support it with the next release

**Comment by boxblinkracer** [comment]
hi

the plugin is now working with shopware 5.7 in the current master branch.

although all automated tests pass, please keep in mind there will be a manual release test run too...
then it will be added to the next version (i think in about a week)

**Comment by boxblinkracer** [comment]
shopware 5.7 support has been released with version 1.8.5
i would now close this ticket
