### ISSUE TITLE
API keys of subshops ignored in 1.5.13

### ISSUE THREAD

**Issue by DenizGelion** [mollie/Shopware#22]
Hi there!
We installed the latest update (1.5.13) on our Shopware 5.6.7 shop and for some reason the plugin seems to ignore all of API keys of our subhops. It only takes the key of the "main" shop into consideration, which means, all of our 3 subshops redirect to the same page (the test key was entered, so all shops end up on the mollie test page after placing an order) on any mollie payment method. Downgrading to 1.5.12 resolved this issue, so I think there's a bug in the latest one. We wanted to activate Klarna Slice it and Pay Later for this, but since you seem to have fixed issues in 1.5.13 we deactivated Klarna services for now.

I would appreciate it, if you could look into this! Thank you very much.

**Comment by julian-kiener** [comment]
Version 1.5.14 of the plugin is ​released this morning. Can you test if this fix the issue for you?

**Comment by DenizGelion** [comment]
Seems to work- thank you for the quick resolution!

**Comment by KienerNL** [comment]
Thanks for your response. Glad it works out for you. Feel free to contact us anytime if anything else comes up.
