### ISSUE TITLE
"The order can't be shipped."

### ISSUE THREAD

**Issue by SandyMental** [mollie/Shopware#228]
Status change to "Completly delivered", does not ship the order in mollie. Same when using the icon in order overview.
This effects Klarna invoice and possibly "Slice it".

Problem exists since release 1.8.0 as far I can remember. Did not pay much attention on it until now I found time to report that.
Shopware 5.6.10,  PHP 7.4.18

Here the error from the logs:
```
{
  "error": "The order can't be shipped.",
  "session": "not-set",
  "processors": {
    "uid": {
      "uid": "bf0eefb"
    },
    "web": {
      "url": "/backend/Order/save?_dc=1623935528011&orderID=&stockChangeWarehouseId=1&pickwareMarkOrderAsShipped=1",
      "ip": "127.0.0.*",
      "http_method": "POST",
      "server": "yourdomain.com",
      "referrer": "https://yourdomain.com/backend/"
    },
    "introspection": {
      "file": null,
      "line": null,
      "class": "MollieShopware\\Subscriber\\OrderBackendSubscriber",
      "function": "shipOrderToMollie"
    }
  }
}
```

**Comment by boxblinkracer** [comment]
Hi

thank you for this,
is that order shippable? i think it might be a "tr_xyz" transaction? these cannot be shipped in Mollie?

it needs to be an "order" in Mollie and must not be shipped already
can you verify this for me?
thanks

**Comment by SandyMental** [comment]
as I see it is an "order"

Should I post the log output from the order creation?

**Comment by boxblinkracer** [comment]
can you open the order in the mollie dashboard and see if it could be shipped there (not the transaction)?
because the error "the order cannot be shipped" ist not really an exception.
it just means its not shippable due to conditions, 

shipping only works for orders, so transactions with a number "ord_xyz"

**Comment by SandyMental** [comment]
Yes it can be shipped in mollie dashboard - did that all the time when this issue came along.

Mollie_id in Shopware orderview says "ord_xyz".

It worked before - I'm confused :shrug:

**Comment by boxblinkracer** [comment]
alright
this is a weird thing

that involves a code i havent been able to refactor yet

I see the error in PaymentService.php, Line 517,
it has an exception but doesnt show or log anything

could you change that to 
throw new \Exception($ex->getMessage());

or just remove the try catch there,

then we know what is really happening in there

and then i know what at least causes the issue, its something in MollieShipping.php with the new tracking.
it has of course all been tested with all known use cases, so i think something weird or new is going on there

we'll get that, no worries :)

**Comment by SandyMental** [comment]
thanks for the swift replies :-)

will change that line and report soon

**Comment by boxblinkracer** [comment]
hi
did a new pull request to at least have the real error in the logs: https://github.com/mollie/Shopware/pull/231
if you know what is happening on your side, then i could try to fix anything if possible, for the next release next week

did you have some time by now?

**Comment by SandyMental** [comment]
I will report during the day.

**Comment by boxblinkracer** [comment]
hi
perfect thanks for this
i got that in and it should be fixed with 1.8.5
the reason can be that your shipping cost has something in the tracking url that might not be a valid URL,
can you check that for me?

besides that 1.8.5 does now validate more strictly the URL that is built for tracking and just skips it if its no real URL...then the error shouldnt occur anymore

still it would be interesting what is in there...

**Comment by SandyMental** [comment]
you mean the tracking-url coming from the shipping-costs module?

looks like this for DHL:
https://nolp.dhl.de/nextt-online-public/de/search?piececode={$offerPosition.trackingcode}

**Comment by boxblinkracer** [comment]
ah perfect
ouch, those other smarty variables....you are right, there are so many different variables that could be in there
so at the moment that would be sent mollie which is obviously no real URL

so 1.8.5 would send it without a URL now,
and I need to figure out a way to render all these smarty variables into a real value :)

i just made support for the ordernumber unfortunately as described here:
https://github.com/mollie/Shopware/wiki/Shipments

do you know what i mean?

**Comment by SandyMental** [comment]
not really but I just tried the variable mentioned in the wiki - {$sOrder.trackingcode} - and it works.

I think this one can be closed, as it's maybe just a matter of knowing what variable really does the trick, instead of implenting support for every known variable ;-)
I'm happy now - thanks again for your support.

**Comment by boxblinkracer** [comment]
ok thank you very much for your feedback

there will be a more flexible support, but for now great its working for you
