### ISSUE TITLE
Apple Pay restrictions cannot be selected when backend is contained in URL multiple times

### ISSUE THREAD

**Issue by fjbender** [mollie/Shopware#237]
In

https://github.com/mollie/Shopware/blob/092f5b807f0803abf4162c6bad57c182013005ae/Resources/config.xml#L632

we try to build the URL for the endpoint to find out about Apple Pay restrictions by doing some `substr` magic on `window.location.href`. That might work, but it doesn't _always_ work. For URLs like `https://backend.my-shop.example/backend` we might not get the expected result. In a distributed Shopware setup it's quite common though to have backend and several frontends.

Maybe we can find another way to figure out the URL.

**Comment by boxblinkracer** [comment]
Hi

correct, multiple instances is common...the backend subdomain is a bad coincidence though ;)

i think that code was taken from some shopware sample.
other config ajax requests have a relative approach

so i think it should just work like this 
`
url: '/backend/MollieApplePayDirect/displayRestrictions'
`

should be an easy improvement, ill check it out

**Comment by boxblinkracer** [comment]
has been released with v1.8.6 and should now work like the other serttings
