### ISSUE TITLE
Since the new update to 1.8.6 klarna checkout isn't working anymore in Shopware 5.7.2

### ISSUE THREAD

**Issue by dennismenken** [mollie/Shopware#247]
Hello mollie-Team.

since the new update the Klarna Checkout (paylater) isn't working anymore. In the history of mollie we see the following message:

GERMAN:
`Verbindung zum Webhook ist mit Status-Code 500 ist fehlgeschlagen (Internal Server Error)`

In the system logs of the mollie plugin we see the following message:

```
Error in Mollie Notification (Session: 14f8...)

{
  "error": "The \"mollie_shopware.basket_service\" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.",
  "session": "14f81b6c1dc507007c5825d27480c554",
  "processors": {
    "uid": {
      "uid": "cf4a63b"
    },
    "web": {
      "url": "/Mollie/notify/transactionNumber/1887",
      "ip": "127.0.0.*",
      "http_method": "GET",
      "server": "www.example.com",
      "referrer": null,
      "unique_id": "YPEseOSGR3nt4DYGr2PrgwAAGi0"
    },
    "introspection": {
      "file": null,
      "line": null,
      "class": "Shopware_Controllers_Frontend_Mollie",
      "function": "notifyAction"
    }
  }
}
```

We reinstalled the plugin. We have cleared all caches and routes. Only Klarna Invoice Purchase seems to be affected.

It works in test mode.

Best regards,
Dennis

**Comment by boxblinkracer** [comment]
Hi

thank you for your message
I have the solution for you. 
So I think this was a combination of Shopware 5.7.2 being released, while the latest Mollie Release was still with 5.7.1 (Klarna has of course been tested)

now to the solution
just open this file on your server (directories are different, but you know what file it is)
https://github.com/mollie/Shopware/blob/master/Resources/services/components/mixed.xml

and search for the "mollie_shopware.basket_service". 
The link I've sent above has the public=true code in that line.
That one should be missing in your version. Add it, maybe clear your caches and it should immediately work again

let me know if this helps you

**Comment by boxblinkracer** [comment]
Hi

We've released 1.8.7 today with only that fix.
So you can also upgrade to that version.

thats the only thing that has changed

thanks for reporting this

**Comment by dennismenken** [comment]
Hello @boxblinkracer

it seems to be working now. Thanks for your fast update.

Best regards and have a nice week,
Dennis

**Comment by boxblinkracer** [comment]
perfect, thanks for letting me know @dennismenken  :)
