### ISSUE TITLE
Shopware Default Field "Paid on" is not set

### ISSUE THREAD

**Issue by DomeDev** [mollie/Shopware#287]
Hi Mollie Team, 
In the backend under orders interface there is a field "Paid on". 
Normally this is set as soon as the payment is completed. 
![grafik](https://user-images.githubusercontent.com/10077977/140748099-0504808d-3b2b-4e66-b9c2-ed2ceadd59ff.png)

This is Shopware standard. It is the field "cleareddate" in the DB table "s_order".

Would be happy if you would implement this. 

Thank you.

**Comment by boxblinkracer** [comment]
Hi @DomeDev 

wow, you are right
i wasnt really aware of that field
fun fact is also why its not filled automatically when doing a "paid" transition

but shouldnt be a problem,

great idea,
thank youu

**Comment by boxblinkracer** [comment]
Hi

the feature has just been implemented and is currently in review.
will come with the next feature
thanks for this

**Comment by boxblinkracer** [comment]
Hi @DomeDev 
I just wanted to reach you and let you know that the pull request for this feature has been merged :)

it will come with the next update
