### ISSUE TITLE
Session is still missing for Transaction: 823. Shopware has already removed that user data!

### ISSUE THREAD

**Issue by SandyMental** [mollie/Shopware#316]
I just need an explanation on what happened there and how to prevent that in the future. it's the first time that happened

Acutally user data is in Shopware, Mollie/Klarna approved the order, just no order was created :/

thanks in advance

EDIT: ok while looking deeper into it, I found out why that happened. The customer started checkout the day before and did not finish instantly, instead waiting another 18 hours to finalize the mollie checkout. of course all session data is lost then.

you can close this. I assume it happens rarely that a customer takes this much time to finalize.

**Comment by boxblinkracer** [comment]
Hi

sorry, I did not see this ticket earlier
Yes, that is unfortunately the dependency on the Shopware session data

but makes totally sense what you say
thank you for editing it and posting the reason :)
