### ISSUE TITLE
Falscher Bestellstatus im Mollie Backend

### ISSUE THREAD

**Issue by deubadario** [mollie/Shopware#327]
Hallo,

manche Bestellungen werden im Mollie backend nicht von „Zugelassen“ auf „Abgeschlossen“ geändert, obwohl sie komplett ausgeliefert sind. 
Aktueller Bestellstatus in Shopware wurde nach Absprache mit Mollie Support von „Komplett abgeschlossen“ zu „Komplett ausgeliefert“ geändert, hat aber nichts gebracht.

Bei Stichproben sieht es aus als hätte Mollie Probleme, wenn es sich um Bestellungen handelt wo es mehrere Tracking ID’s gibt.  

Eine weitere Vermutung:
Bei Produkten die eine SKU (Produkt - Ordernumber) haben aber aus mehreren Teilen bestehen wie z.B. Garten-Sitzgruppe die mehrere Tracking ID’s hat (6) weil es sich um mehrere Pakete handelt.

**Comment by boxblinkracer** [comment]
Hallo

Danke für deine Nachricht

wenn es von Authorized nicht auf Paid springt, im Mollie Dashboard es aber sehr wohl abgeschlossen ist, dann liegt es an fehlerhaften Webhooks. Da bitte in die Zahlung im Mollie Dashboard gehen und prüfen ob in der History ein Fehler bei Webhooks war.

Wenn es im Dashboard von Mollie auch noch immer auf Authorized steht, dann wurde kein Shipping gestartet.
Da wäre die Frage wie das bei euch funktioniert. Wenn es vom Shop aus gemacht wird (manuell, automatisch, wie auch immer) muss es auf alle Fälle Log Einträge mit Fehlern geben.
findet ihr da was?

kann gut sein, dass hier eventuell eine Exception passiert bei mehrfach Tracking IDs....

lg
Christian

**Comment by boxblinkracer** [comment]
Der Tracking Fehler mit Codes die länger als 100 Zeichen sind wurde heute mit v2.1.0 released.
Ich würde das Ticket nun erstmal schließen.

einfach wieder melden wenn was ist  :)
