### ISSUE TITLE
Mollie Prepayment: $Mollie.bank.exists not set in email template

### ISSUE THREAD

**Issue by florianliebig** [mollie/Shopware#331]
Wir haben versucht, die Zahlart mollie_prepayment mit den E-Mail Variablen wie in https://github.com/mollie/Shopware/wiki/SEPA-Bank-Transfer#raw-values beschrieben aufzusetzen.

Die Variable ist aber in unseren Tests nie gesetzt.

Hier einige Plugin Einstellungen:

![2022-06-13 at 15 42](https://user-images.githubusercontent.com/10775702/173367154-f12bfcf7-76c6-459b-b0d0-5bdf4406ffd5.jpg)

![2022-06-13 at 15 43](https://user-images.githubusercontent.com/10775702/173367274-e5b7f39a-f0fd-41af-aa90-213fae765951.jpg)

The Shopware Mollie Log didn't show any errors. The payment in mollie shows the correct amount. We also always get the mail from mollie - do we need to adjust the settings in the account?

**Comment by boxblinkracer** [comment]
Hi

thanks for your message

mhm....I think we would need to double check it on our side.
There was no change in that area as far as I know..
What Shopware version and plugin version do you use? then we can test it

thanks

**Comment by florianliebig** [comment]
Hi @boxblinkracer we use 5.7.7 with mollie in 2.0.0.

Thanks in advance

**Comment by boxblinkracer** [comment]
Hi

sorry for the delay @florianliebig 
it worked in your shopware version and plugin version for me (see screenshot)

do you use the sOrder email template?

<img width="1399" alt="MailCatcher__3__and_SEPA_Bank_Transfer_·_mollie_Shopware_Wiki-2" src="https://user-images.githubusercontent.com/5579326/175559104-9e3572cf-d47d-4cd7-828f-a1ebda21b075.png">

**Comment by florianliebig** [comment]
![2022-06-24 at 17 09](https://user-images.githubusercontent.com/10775702/175564403-5fb9ba68-4379-4726-9c39-46bf6aa9460f.jpg)

@boxblinkracer Yes we use the regular sORDER - but only in Plaintext mode (I think this should not be relevant)

![2022-06-24 at 17 10](https://user-images.githubusercontent.com/10775702/175564559-b25580ff-076b-4b8d-90c2-500f274309da.jpg)

**Comment by boxblinkracer** [comment]
thank you for this great call @florianliebig 
to everyone -> we found a bug related to a configuration that is indeed very hidden and unlikely
heres the easy fix -> https://github.com/mollie/Shopware/pull/333
it worked during the demo, florian still needs to verify in his shop

**Comment by boxblinkracer** [comment]
released in 2.1.0

**Comment by florianliebig** [comment]
@boxblinkracer Although we updated to 2.1.0 we still face that issue. This week I will check it on our testserver and report if there is any problem in code

**Comment by boxblinkracer** [comment]
Hi @florianliebig 
thank you

but havent we finished at that place that we know it's a bug but also (still) different in your case
and you know the part in the code where to debug?
i think you wanted to debug and let me know what is wrong in that code for your specific shop?

**Comment by boxblinkracer** [comment]
thank you @florianliebig :)

**Comment by florianliebig** [comment]
![2022-08-29 at 16 07](https://user-images.githubusercontent.com/10775702/187220524-c0c244f9-fad1-4061-88f9-7fb9ecb8216b.png)

NULL int(100000557)

Looking it up by hand in s_order db:

![2022-08-29 at 16 09](https://user-images.githubusercontent.com/10775702/187220935-c2d25cba-e6e2-497f-8612-fbad12fa28cc.png)


It doesnt seem to persist the order ID mol_sw_transactions before sending the mail

**Comment by florianliebig** [comment]
![2022-08-29 at 16 11](https://user-images.githubusercontent.com/10775702/187221497-61eca645-8c23-42fd-8528-fd7e3e320f72.png)

Missed the last screenshot

**Comment by florianliebig** [comment]
![2022-08-29 at 16 13](https://user-images.githubusercontent.com/10775702/187221826-9ef5deb1-12a6-4339-b244-20ec96c78ac4.png)

Einmal noch die Mollie Plugin Settings, falls das irgendwelche Auswirkungen hat

**Comment by boxblinkracer** [comment]
Hi @florianliebig 
danke
hat doch noch damit zu tun dass ja die transaction über methods per REF-ID drin ist
habe denke ich schon eine idee

ps musste deinen letzten post löschen, da der Test-API Key sichtbar war

**Comment by florianliebig** [comment]
![2022-08-29 at 16 15](https://user-images.githubusercontent.com/10775702/187222150-9449a5b4-c947-4d0e-878a-f4fc0a47627b.png)

Lasse ich das var_dump - die im getBankTransferVariables weg ist die Order ID nach vollständiger Abwicklung drin.

![2022-08-29 at 16 16](https://user-images.githubusercontent.com/10775702/187222354-98eaa08b-f2ef-4985-9d69-cccc7759e76f.png)

Hier ohne den Token sorry

**Comment by boxblinkracer** [comment]
hehe perfekt danke @florianliebig 
also der fix damals war genau über die richtige ID gehen
ich denke aber (wenn ich mir den kommentar über den fix ansehe)
dass der fix schon passt , aber in kombi mit "Shopware Bestellung vor Zahlung anlegen NEIN" via Race-Condition zu dem Fehler führt :)

ich denke es sollte dann reproduzierbar und behebbar sein,
danke für deine hilfe

**Comment by boxblinkracer** [comment]
Hi there
alright, so the last (and reproducable) edge case with combination of "mollie payment reference IDs" + "create order AFTER payment" was released in v2.2.0 today

**Comment by florianliebig** [comment]
Verified on live - works now as expected! Thanks a lot

**Comment by boxblinkracer** [comment]
finally :) 
thanks @florianliebig
