### ISSUE TITLE
Fatal Error on CreditCardService

### ISSUE THREAD

**Issue by dbMario** [mollie/Shopware#345]
Since last update, we have some PHP Fatal Errors:

`PHP Fatal error: Uncaught Error: Call to a member function getNumber() on null in /xxxx/custom/plugins/MollieShopware/Components/Services/CreditCardService.php:94\nStack trace:\n#0 /xxxx/custom/plugins/MollieShopware/Facades/CheckoutSession/CheckoutSessionFacade.php(202): MollieShopware\\Components\\Services\\CreditCardService->getCardToken()\n#1 /xxxx/custom/plugins/MollieShopware/Controllers/Frontend/Mollie.php(166): MollieShopware\\Facades\\CheckoutSession\\CheckoutSessionFacade->startCheckoutSession()\n#2 /xxxx/engine/Library/Enlight/Controller/Action.php(186): Shopware_Controllers_Frontend_Mollie->directAction()\n#3 /xxxx/engine/Library/Enlight/Controlle in /xxxx/custom/plugins/MollieShopware/Components/Services/CreditCardService.php on line 94`

I search for the reason and found 2 Apple Pay Direct transactions with this error.

I think a fix in CreditCardService.php is required.
if $customer is null = return like false is needed.

**Comment by boxblinkracer** [comment]
Hi @dbMario 

ok this is the first time i saw this.
I'll mark it as bug and see what happens.

the basic approach of coding is fail-fast, so im not quite sure if a check for a null customer is good or if it just wraps a bigger problems

thanks for letting us know

**Comment by boxblinkracer** [comment]
Imprvement released in v2.2.0
thank you for your help :)
