### ISSUE TITLE
Wrong Language in Lang-Sub-Shops

### ISSUE THREAD

**Issue by dbMario** [mollie/Shopware#346]
Hi,

we have some subshops for french, italian and more.
but in every shop we get german text on apple pay direct button.

why?
in **mollie_applepay_direct.tpl** on line 2, lang was set with **$smarty.server.HTTP_ACCEPT_LANGUAGE**
But on every subshop we had an header with **Accept-Language: de-DE**, so we get in this variable de-DE every time.

If i change to **$Locale**, i will get the right language in button.

I think this must be fix or did you see other problems?

**Comment by boxblinkracer** [comment]
Hi @dbMario 

ah cool, it could indeed be that the global internationalization needs some tweaks

i'll mark it to be coded, or do you already know the solution and can provide a PR?

**Comment by dbMario** [comment]
Hi @boxblinkracer 

File: Resources/views/frontend/plugins/payment/mollie_applepay_direct.tpl
Line 2: change {$smarty.server.HTTP_ACCEPT_LANGUAGE} to {$Locale}

**Comment by boxblinkracer** [comment]
thank you @dbMario 
will be rolled out with the upcoming release

**Comment by boxblinkracer** [comment]
Released in v2.2.0
thank you for your help :)
