### ISSUE TITLE
No payment status email send

### ISSUE THREAD

**Issue by githuphub** [mollie/Shopware#349]
Hi,

I've been trying to get the payment status updates to work, emails are not send when the status changes. Only when I do it manually Shopware gives me the pop-up with the email template. 

We are running version 1.8.12, email template for this status (35 - Order has been cancelled) added. The error I get on return cancelling the order: 

{
  "error": "Payment failed for transaction: tr_removed, The payment failed. Please see the Mollie Dashboard for more!",
  "session": "removed",
  "processors": {
    "uid": {
      "uid": "3c2701f"
    },
    "web": {
      "url": "/Mollie/finish/transactionNumber/3005",
      "ip": "127.0.0.*",
      "http_method": "GET",
      "server": "removed",
      "referrer": "https://ideal.ing.nl/"
    },
    "introspection": {
      "file": null,
      "line": null,
      "class": "Shopware_Controllers_Frontend_Mollie",
      "function": "finishAction"
    }
  }
}

Any idea what could be wrong? Thank you!

**Comment by boxblinkracer** [comment]
hi

there is a plugin configuration to also send payment status updates
have you seen this? maybe this is what you need?

heres a link: https://github.com/mollie/Shopware/wiki/Plugin-Configuration

**Comment by githuphub** [comment]
Thank you!
