### ISSUE TITLE
Error Messages : Mollie/components?ext=.js&ts=1706538991

### ISSUE THREAD

**Issue by oremountains** [mollie/Shopware#399]
Since update 2.5 there have been persistent error messages

**<html><body>

Message: | Unable to load template snippet 'frontend/mollie/components.tpl\|frontend/plugins/seo/index.tpl'
-- | --
2024-01-29T15:36:33.483993+0100
core
{     "uri": "/Mollie/components?ext=.js&ts=1706538991",     "method": "GET",     "query": {         "ext": ".js",         "ts": "1706538991",         "module": "frontend",         "controller": "Mollie",         "action": "components"     },     "post": []

</body>
</html>**

**Comment by rkemmere** [comment]
We have the same issue on shopware 5 latest version and on mollie version 2.5

**Comment by BlackScorp** [comment]
hi sorry for this, i create a hotfix ASAP, will be fixed in new version
