### ISSUE TITLE
Error: No option the entry creditcard number

### ISSUE THREAD

**Issue by rkemmere** [mollie/Shopware#400]
Latest Shopware and Mollie Version 2.5.

In the checkout process the creditcard fields are not clickable. 
There are only a div for credit card number and no input fields. Seems that the Javascript will not load the rest. 

It's an urgent problem!

**Comment by fjbender** [comment]
Hi, unfortunately, we're not able to provide support for urgent issues through Github - please reach out to our support team instead. In the meantime, to not lose any payments, disable Mollie Components to revert back to the Hosted Payment Page.
