### ISSUE TITLE
version 2.5.2 blik cannot be activated

### ISSUE THREAD

**Issue by oremountains** [mollie/Shopware#411]
After activating **blik** in the Mollie portal, the Blik payment method is not displayed 
in the payment method (after updating the payment methods)

**Comment by fjbender** [comment]
Blik unfortunately isn't support in this plugin. :( 

If you look at #388 the implementation should be pretty similar though.

**Comment by BlackScorp** [comment]
@oremountains Blik is currently only available for shopware 6
