### ISSUE TITLE
Stock bug 

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/Shopware#60]
Hello,
I'm getting in touch because I have noticed a very weird behavior with Shopware 6 .

Take a look at this scenario:
I have a "product A" with stock of 10 and set as closeout.
As a customer, I add product A to my cart, I click "pay" (with Mollie) when I am redirected to Mollie, the stock becomes minus 1 even if I haven't paid !
Next customer does the same thing but puts 9 remaining product A to his basket. 
Shopware sets the stock to 0. 
Third customer comes and nobody can buy product A anymore. And nobody has paid anything. 
Am I clear in my explanations, is it me doing something wrong or it's a bug ?

**Comment by boxblinkracer** [comment]
Hi
thank you marcel,
that explanation is great.
there is indeed a ticket that is in investigation about some weird behaviour with the stock.
your step by step guide should defnitely help

question...there is the option to "reset the stock on failed payments". in your case its about successful payments, that might not have been finised yet, right?


the tickets for the upcoming release are already closed.
afterwards we'll continue with the stock problems (just to let you know)

thank you

**Comment by powolnymarcel** [comment]
I've set up Mollie to put the cancelled status on failed payments
https://i.ibb.co/9btTkHH/Capture2.png

As you can see here some customers attempted to buy something but for any reason changed their mind and the order is still "in progress"
https://i.ibb.co/w7MxTq6/Capture.png

The Mollie timeout is 15min right ?

**Comment by boxblinkracer** [comment]
Hi

oh, is this also shopware 6?
could you add an issue here: https://github.com/mollie/Shopware6

sorry for this, but we are 2 agencies, and we do only maintain shopware 5 for mollie

cheer
christian

**Comment by powolnymarcel** [comment]
Ok sorry didn't noticed. You can delete this if you want ;)

Thanks for the attention and answers :)

**Comment by boxblinkracer** [comment]
your welcome 
thank you too
