### ISSUE TITLE
Could not create a Mollie Payment Url due to VAT amount mismatch

### ISSUE THREAD

**Issue by ionics** [mollie/Shopware#73]
similar to: https://github.com/mollie/OpenCart/issues/143

Error: 
Could not create a Mollie Payment Url, error: Could not create Mollie order, error: Error executing API call (422: Unprocessable Entity): Order line 2 is invalid. VAT amount is off. Expected VAT amount to be -€6.08 (-€36.50 × (20.00% / 120.00%)), got -€6.09. Field: lines.2.vatAmount. Documentation: https://docs.mollie.com/guides/handling-errors

Expected result:
Cent values must match. Checkout must succeed without issues.

**Comment by boxblinkracer** [comment]
Hi

thank you so much for this
we know this problem, but more likely in Shopware 6

is this shopware 5 or 6?

This repository is only for Shopware 5

best regards
Christian

**Comment by ionics** [comment]
shopware 6 - sorry, but please move to right location!

**Comment by boxblinkracer** [comment]
hi
dont worry, i'll let the shopware 6 guys know
