### ISSUE TITLE
Understand problem with shipping status options

### ISSUE THREAD

**Issue by larsbo** [mollie/Shopware#75]
This is more a documention related issue but maybe you can explain it (as the customer support cannot 😄 ):
What is the difference between the two settings
- "Order Status" for shipped orders
- Status on which order is marked as "sent"

I read the documentation here https://github.com/mollie/Shopware/wiki/Plugin-Configuration#shipping several times but it sounds as if this two options are totally the same?
Currently we set the same delivery status but maybe this is wrong? Maybe you can give an example that explains what both options do?

**Comment by boxblinkracer** [comment]
Hi

thank you for this, i do also have that "problem" since we took over the plugin maintenance.
my wish is to somehow refactor these 2 settings to have it more clear

i will check it out and let you know

**Comment by larsbo** [comment]
Ok, I understand. So it looks as if they do the same but maybe there is some not detected reason for the existence of both?

**Comment by boxblinkracer** [comment]
so

Status on which order is marked as sent (Klarna Pay Later):
"klarna_ship_on_status" is the status that is the trigger that a shipping is being executed.

Order status for shipped orders (Klarna Pay Later):
"klarna_shipped_status" is the status that it will get, if a webhook or event from Mollie tells Shopware that the order is "shipped".

i hope this helps you

**Comment by larsbo** [comment]
Yes, in other words
`klarna_ship_on_status` is for Shopware -> Mollie communication
`klarna_shipped_status` is for Mollie -> Shopware communication

And there will be no deadlock if both settings have the same status, I guess 😉

**Comment by boxblinkracer** [comment]
yes thats correct
at the moment there won't be a deadlock, but we are doing the shopware->mollie trigger in a better way, so that all transitions are supported

i think these are 2 different settings. one says "ready to ship" the other one says "shipped"
so you have both of them...

i will make sure that we only trigger events on transitions from a different status, that should avoid dead locks

**Comment by boxblinkracer** [comment]
figured out how it works and did a better integration and documentation for that setting
https://github.com/mollie/Shopware/wiki/Plugin-Configuration
